---
hostname: blackbox-1

# -|----------------------------------------------------------------------------
#  | Device Settings
# -|----------------------------------------------------------------------------
#  |  Set the hardware adapters here
#  |     - `wifi_adapter` is the device which will be used to create a wifi network
#  |     - `lan_adapter`  is the device that is connected to the internet
#  |
wifi_adapter: wlan0
lan_adapter: eth0
otg_adapter: usb0

# -|----------------------------------------------------------------------------
#  | Static IP settings for the lan_adapter
# -|----------------------------------------------------------------------------
#  |  If you want the lan_adapter (the one connecting your access point to a
#  |  router) to have a fixed ip address, you can configure this here.
#  |     - `enabled` set this to `True` to enable static ip configuration
#  |     - `address` the ip address of the adapter
#  |     - `netmask` the corresponding subnet mask
#  |     - `gateway` ip address of the router
#  |
lan_static:
  enabled: False
  address: 192.168.0.2
  netmask: 255.255.255.0
  gateway: 192.168.0.1


# -|----------------------------------------------------------------------------
#  | Wifi Settings
# -|----------------------------------------------------------------------------
#  |  Configuration options for your access point.
#  |
#  |     `ssid`: the "name" of the wifi networks as it appears in the
#  |             list of available networks on client devices
#  |
#  |     `channel`: the wifi channel that will be used
#  |
#  |     `security.enabled`: set to `True` to enable WPA-2 encryption
#  |     `security.psk`: the "password" for the network
#  |                     (ignored if security.enabled == False)
#  |
ssid: blackbox-1
channel: 6

security:
  enabled: True
  psk: blackbox  # The "password" for the network (at least 8 characters)

wifi_country: IT

# -|----------------------------------------------------------------------------
#  | DHCP Settings
# -|----------------------------------------------------------------------------
#  |  Settings for the local dhcp server. Configure
#  |  address range, gateway, etc. here.
#  |
#  |
ip_base: 192.168.1
own_ip: "{{ ip_base }}.1"
ip_range:
  start: "{{ ip_base }}.20"
  end: "{{ ip_base }}.254"
dns_servers: "192.168.1.1"
subnet: 255.255.255.0
network: "{{ ip_base }}.0"
broadcast: "{{ ip_base }}.255"
lease_time: 864000  # That's how many seconds are in 10 days
domain: costigiola.net

# -|----------------------------------------------------------------------------
#  | Tweaks
# -|----------------------------------------------------------------------------
#  |  Some advanced options for special cases
#  |
#  |     `disable_wmm`: Set to `True` to disable QoS
#  |
disable_wmm: True

cmdline_options:
 - zswap.enabled=1
 - modules-load=dwc2,g_ether

boot_options:
 - "dtoverlay=dwc2"

webserver_static_sites:
  - name: studio.code.org
    root: /usr/share/nginx/studio.code.org
  - name: www.bitprepared.it
    root: /usr/share/nginx/www.bitprepared.it
 
webserver_static_sites_with_game: 
- name: blackbox.costigiola.net
  root: /usr/share/nginx/blackbox.costigiola.net
  rootGame: /usr/share/nginx/blackbox.costigiola.net/StarQuiz
# - name: oro.costigiola.net
#   root: /usr/share/nginx/oro.costigiola.net
#   rootGame: /usr/share/nginx/oro.costigiola.net/giocooca
# - name: rosso.costigiola.net
#   root: /usr/share/nginx/rosso.costigiola.net
#   rootGame: /usr/share/nginx/rosso.costigiola.net/SpaceShooter
# - name: arancio.costigiola.net
#   root: /usr/share/nginx/arancio.costigiola.net
#   rootGame: /usr/share/nginx/arancio.costigiola.net/Cluedo
# - name: blu.costigiola.net
#   root: /usr/share/nginx/blu.costigiola.net
#   rootGame: /usr/share/nginx/blu.costigiola.net/StickFighter

# roles/dnsmasq/defaults/main.yml
dnsmasq_domain_needed: true
dnsmasq_bogus_priv: true
dnsmasq_authoritative: true
dnsmasq_expand_hosts: false
dnsmasq_domain: costigiola.net
dnsmasq_addn_hosts: true
dnsmasq_listen_address: 192.168.1.1
dnsmasq_interface: wlan0

#B1 cli, B2 cli autologin, B3 desktop, B4 desktop autologin
BOOTBEHAVIOUR: B1 
